# -*- coding: utf-8 -*-
"""MADS-Grupo2-DEV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reJ6kA1Kry3QVgQ4qkNppwEY4h-OOl8d

# Gestão e verificador de Valores de Superficies comerciais
Trabalho desenvolvido no ambito da unidade curricular Metodologias Ágeis de Desenvolvimento de Software pelos alunos


*   João Martins – A045027
*   José Mendonça – A045709
*   Rodrigo Santos – A044771
*   Mário Pinto – A045835

A ideia por de trás deste projecto é desenvolver um sistema onde seja possivel adicionar compras feitas por utilizadores em lojas e, com base nesses dados, seja possivel comprar entre lojas os mesmos productos.

Gostavamos de deixar frisado que o nosso sistema de erros teve como inspiração o sistema de erros inplementado no trabalho do Grupo 1 que agilisou e tornou mais facil a representação dos mesmos.
Foi usado como ajuda na criação da zona de testes e revisão do codigo ferramentas de inteligencia artificial como o Gemini e o ChatGpt no entanto nos (João Martins – A045027, José Mendonça – A045709, Rodrigo Santos – A044771, Mário Pinto – A045835) somos inteiramente responsaveis por todo o codigo aqui presente e assumimos a responsabilidade do mesmo.

# Bibliotecas
"""

import json
from datetime import datetime
import matplotlib.pyplot as plt
import re

"""# "Base de Dados"
"""

utilizadores = {}
categoriasLojas = ["Padaria", "Talho", "Peixaria", "Supermercado"]
lojas = {}
compras = {}

"""# Adicionar Utilizadores"""

def add_user(nome: str, nif: str, data_nasc: str, sexo: str):
  erros =[]
#Verificação de campos totais
  if not nome or not nif or not data_nasc or not sexo:
    erros.append("Erro: Todo os campos são de preenchimento obrigatório")

#Verificações do nome
  if not isinstance(nome, str):
      erros.append("Erro: O nome deve ser texto.")
  elif not re.fullmatch(r"[A-Za-zÀ-ÖØ-öø-ÿ\s]+", nome):
      erros.append("Erro: O nome não pode conter números ou caracteres especiais.")

#Verificação do NIF
  if not isinstance(nif, str):
      erros.append(f"Erro: O NIF - {nif} - deve ser texto.")
  elif not nif.isdigit():
      erros.append(f"Erro: O NIF - {nif} - deve conter apenas números.")
  elif len(nif) != 9:
      erros.append(f"Erro: O NIF - {nif} - deve ter exatamente 9 dígitos.")
  elif nif in utilizadores:
      erros.append(f"Erro: Esse NIF - {nif} - já está registado!")

#Verificação da Idade/Data de nascimento
  idade = 0
  if not re.match(r"^\d{2}-\d{2}-\d{4}$", data_nasc):
        erros.append("Erro: A data de nascimento deve estar no formato DD-MM-YYYY.")
  else:
        try:
            data_convertida = datetime.strptime(data_nasc, "%d-%m-%Y").date()
            hoje = datetime.now().date()

            if data_convertida > hoje:
                erros.append("Erro: A data de nascimento não pode ser de uma data futura.")
            else:
                idade = hoje.year - data_convertida.year - ((hoje.month, hoje.day) < (data_convertida.month, data_convertida.day))
                if idade <= 0:
                    erros.append("Erro: A idade tem de ser superior a 0 anos.")
        except ValueError:
            erros.append("Erro: Data de nascimento inválida.")

#Verificação dos dados de sexo
  sexos_validos = ["M", "F", "O"]
  if isinstance(sexo, str) and sexo.upper() not in sexos_validos:
      erros.append("Erro: Sexo inválido. Use 'M', 'F' ou 'O'.")

#Lista de erros, se existirem
  if erros:
        for erro in erros:
            print(f"- {erro}")
        return

#Registro do Utilizador após todas as verificações
  utilizadores[nif] = {
        "nome": nome.strip(),
        "idade": idade,
        "sexo": sexo.upper()
  }
  print(f"Sucesso: Foi registrado um utilizador com o nome '{nome.strip()}' e NIF: {nif}")

"""# Registrar loja"""

contador_lojas = 1

def add_loja(nome: str, especialidade: str, localizacao: str):
    global contador_lojas
    erros = []

#Verificação de campos totais
    if not nome or not especialidade or not localizacao:
        erros.append("Erro: Todos os campos são de preenchimento obrigatório.")

#Verificações do Nome da Loja
    if not isinstance(nome, str):
        erros.append("Erro: O nome da loja deve ser texto.")
    elif not re.fullmatch(r"[A-Za-zÀ-ÖØ-öø-ÿ0-9\s\&]+", nome):
        erros.append("Erro: O nome da loja contém caracteres inválidos.")

#Verificações da Localização
    if not isinstance(localizacao, str):
        erros.append("Erro: A localização deve ser texto.")
    elif not re.fullmatch(r"[A-Za-zÀ-ÖØ-öø-ÿ\s\-]+", localizacao):
        erros.append("Erro: A localização contém caracteres inválidos (ex: números).")

#Verificações da Especialidade
    if isinstance(especialidade, str):
        especialidade_formatada = especialidade.strip().capitalize()
        if especialidade_formatada not in categoriasLojas:
            erros.append(f"Erro: Especialidade inválida. Escolha uma das seguintes: {', '.join(categoriasLojas)}.")
    else:
        erros.append("Erro: A especialidade deve ser texto.")

#Só fazemos a procura se o nome e localização forem efetivamente texto válido
    if isinstance(nome, str) and isinstance(localizacao, str) and nome and localizacao:
        for loja_existente in lojas.values():
            if loja_existente["nome"].lower() == nome.strip().lower() and loja_existente["localizacao"].lower() == localizacao.strip().lower():
                erros.append(f"Erro: A loja '{nome.strip()}' em '{localizacao.strip()}' já se encontra registada!")
                break

#Lista de erros, se exixtirem
    if erros:
        for erro in erros:
            print(f"- {erro}")
        return

#Registro da Loja após todas as verificações
    lojas[contador_lojas] = {
        "nome": nome.strip(),
        "especialidade": especialidade_formatada,
        "localizacao": localizacao.strip()
    }

    print(f"Sucesso: A Loja '{nome.strip()}' registada com o ID: {contador_lojas}")

    contador_lojas += 1

"""# Registrar Compra"""

contador_compras = 1

def add_compra(produto: str, preco: float, id_loja: int, data_compra: str, nif_utilizador: str, tipo_pagam: str = ""):
    global contador_compras
    erros = []

#Verificação de campos totais (Sem tipo de pagamento pois isso é opcional)
    if not produto or not preco or not id_loja or not data_compra or not nif_utilizador:
        erros.append("Erro: Produto, Preço, ID da Loja, Data e NIF do Utilizador são obrigatórios.")

#Verificações do Produto
    if not isinstance(produto, str):
        erros.append("Erro: O nome do produto deve ser texto.")
    elif not re.fullmatch(r"[A-Za-zÀ-ÖØ-öø-ÿ0-9\s\-]+", produto):
        erros.append("Erro: O nome do produto contém caracteres inválidos.")

#Verificações do Preço
    if not isinstance(preco, (int, float)):
        erros.append("Erro: O preço deve ser um valor numérico (inteiro ou decimal).")
    elif preco <= 0:
        erros.append("Erro: O preço tem de ser estritamente superior a 0.")

#Verificações do ID da Loja
    if isinstance(id_loja, int):
        if id_loja not in lojas:
            erros.append(f"Erro: Não existe nenhuma loja registada com o ID {id_loja}. Registe a loja primeiro.")
    else:
        erros.append("Erro: O ID da loja deve ser um número inteiro.")

# Verificação do NIF
    if isinstance(nif_utilizador, str):
        if nif_utilizador not in utilizadores:
            erros.append(f"Erro: Não existe nenhum utilizador com o NIF {nif_utilizador}. Registe o utilizador primeiro.")
    else:
        erros.append("Erro: O NIF do utilizador deve ser texto.")

#Verificações da Data da Compra
    if isinstance(data_compra, str):
        if not re.match(r"^\d{2}-\d{2}-\d{4}$", data_compra):
            erros.append("Erro: A data da compra deve estar no formato DD-MM-YYYY.")
        else:
            try:
                data_convertida = datetime.strptime(data_compra, "%d-%m-%Y").date()
                hoje = datetime.now().date()
                if data_convertida > hoje:
                    erros.append("Erro: A data da compra não pode ser no futuro.")
            except ValueError:
                erros.append("Erro: Data de compra inválida.")
    else:
        erros.append("Erro: A data da compra deve ser texto no formato DD-MM-YYYY.")

#Verificações do Tipo de Pagamento
    if tipo_pagam:
        if not isinstance(tipo_pagam, str):
            erros.append("Erro: O tipo de pagamento deve ser texto ('N' ou 'M').")
        elif tipo_pagam.strip().upper() not in ["N", "M"]:
            erros.append("Erro: Tipo de pagamento inválido. Use 'N' para Numerário ou 'M' para Multibanco.")

#Lista de erros, se existirem
    if erros:
        for erro in erros:
            print(f"- {erro}")
        return

#Formatação do tipo de pagamento
    if tipo_pagam.strip().upper() == "N":
        pagamento_final = "Numerário"
    elif tipo_pagam.strip().upper() == "M":
        pagamento_final = "Multibanco"
    else:
        pagamento_final = "Não especificado"

#Registro da Compra após todas as verificações
    compras[contador_compras] = {
        "nif_utilizador": nif_utilizador.strip(),  # <-- GUARDADO AQUI
        "produto": produto.strip().lower(),
        "preco": float(preco),
        "id_loja": id_loja,
        "data": data_compra.strip(),
        "tipo_pagam": pagamento_final
    }

    nome_loja = lojas[id_loja]["nome"]
    nome_user = utilizadores[nif_utilizador]["nome"]
    print(f"Sucesso: Compra de '{produto.strip().capitalize()}' registada por {nome_user} na loja '{nome_loja}'! (ID: {contador_compras})")

    contador_compras += 1

"""# Listagens"""

def listar_dados(entidade: str, ordem: str = "asc", filtro_tipo: str = "", filtro_valor: str = ""):
    erros = []
    entidades_validas = ["utilizadores", "lojas", "compras"]

#Verificação da entidade solicitada
    if not isinstance(entidade, str):
        erros.append("Erro: A entidade deve ser texto.")
    elif entidade.strip().lower() not in entidades_validas:
        erros.append(f"Erro: Entidade inválida. Escolha entre: {', '.join(entidades_validas)}.")

#Verificação e conversão da ordem (asc/desc para boolean)
    ordem_descendente = False
    if isinstance(ordem, str):
        if ordem.strip().lower() == "desc":
            ordem_descendente = True
        elif ordem.strip().lower() != "asc":
            erros.append("Erro: A ordem de listagem deve ser 'asc' ou 'desc'.")
    else:
        erros.append("Erro: A ordem deve ser texto ('asc' ou 'desc').")

#Lista de erros, se existirem
    if erros:
        for erro in erros:
            print(f"- {erro}")
        return

    entidade_formatada = entidade.strip().lower()

#Listar Utilizadores
    if entidade_formatada == "utilizadores":
        if not utilizadores:
            print("Aviso: Ainda não existem utilizadores registados.")
            return

        print(f"\n--- LISTA DE UTILIZADORES ---")
        itens = sorted(utilizadores.items(), reverse=ordem_descendente)
        resultados = 0

        for nif, dados in itens:
            if filtro_tipo.lower() == "sexo" and dados['sexo'] != filtro_valor.strip().upper():
                continue

            print(f"NIF: {nif} | Nome: {dados['nome']} | Idade: {dados['idade']} anos | Sexo: {dados['sexo']}")
            resultados += 1

        if resultados == 0:
            print("Nenhum utilizador encontrado com esses critérios.")

#Listar Lojas
    elif entidade_formatada == "lojas":
        if not lojas:
            print("Aviso: Ainda não existem lojas registadas.")
            return

        print(f"\n--- LISTA DE LOJAS ---")
        itens = sorted(lojas.items(), reverse=ordem_descendente)
        resultados = 0

        for id_loja, dados in itens:
            if filtro_tipo.lower() == "especialidade" and dados['especialidade'].lower() != filtro_valor.strip().lower():
                continue

            print(f"ID: {id_loja} | Nome: {dados['nome']} | Especialidade: {dados['especialidade']} | Localização: {dados['localizacao']}")
            resultados += 1

        if resultados == 0:
            print("Nenhuma loja encontrada com esses critérios.")

#Listar Compras
    elif entidade_formatada == "compras":
        if not compras:
            print("Aviso: Ainda não existem compras registadas.")
            return

        print(f"\n--- LISTA DE COMPRAS ---")
        itens = sorted(compras.items(), reverse=ordem_descendente)
        resultados = 0

        for id_compra, dados in itens:
            if filtro_tipo.lower() == "produto" and dados['produto'] != filtro_valor.strip().lower():
                continue
            elif filtro_tipo.lower() == "loja" and str(dados['id_loja']) != str(filtro_valor).strip():
                continue
            elif filtro_tipo.lower() == "pagamento" and dados['tipo_pagam'].lower() != filtro_valor.strip().lower():
                continue
            elif filtro_tipo.lower() == "com_pagamento_registado" and dados['tipo_pagam'] == "Não especificado":
                continue
            elif filtro_tipo.lower() == "nif" and str(dados.get('nif_utilizador', '')) != str(filtro_valor).strip():
                continue

            nome_loja = lojas[dados['id_loja']]["nome"]
            # Captura o nome do utilizador para mostrar na listagem
            nif_comp = dados.get('nif_utilizador', '')
            nome_user = utilizadores[nif_comp]["nome"] if nif_comp in utilizadores else "Desconhecido"

            produto_formatado = dados['produto'].capitalize()

            # Print atualizado com o nome do comprador
            print(f"ID: {id_compra} | Produto: {produto_formatado} | Preço: {dados['preco']:.2f}€ | Comprador: {nome_user} | Loja: {nome_loja} | Data: {dados['data']} | Pagamento: {dados['tipo_pagam']}")
            resultados += 1

        if resultados == 0:
            print("Nenhuma compra encontrada com esses critérios.")

"""# Exportação de dados em Json"""

def exportar_para_json(nome_ficheiro: str = "dados_plataforma.json", entidade: str = "tudo", filtro_tipo: str = "", filtro_valor: str = ""):
    erros = []

#Verificação do nome do ficheiro
    if not isinstance(nome_ficheiro, str):
        erros.append("Erro: O nome do ficheiro deve ser texto.")
    elif not nome_ficheiro.endswith(".json"):
        erros.append("Erro: O nome do ficheiro tem de terminar obrigatoriamente em '.json'.")

#Lista de erros, se existirem
    if erros:
        for erro in erros:
            print(f"- {erro}")
        return

    dados_para_exportar = {}
    entidade_formatada = entidade.strip().lower()

#Cenário 1: Exportação Total
    if entidade_formatada == "tudo":
        dados_para_exportar = {
            "utilizadores": utilizadores,
            "categoriasLojas": categoriasLojas,
            "lojas": lojas,
            "compras": compras
        }
        mensagem = "Todos os dados da plataforma (Exportação Integral)"

#Cenário 2: Exportar Apenas Compras Filtradas
    elif entidade_formatada == "compras":
        compras_filtradas = {}
        for id_compra, dados in compras.items():
            if filtro_tipo.lower() == "produto" and dados['produto'] != filtro_valor.strip().lower():
                continue
            elif filtro_tipo.lower() == "loja" and str(dados['id_loja']) != str(filtro_valor).strip():
                continue
            elif filtro_tipo.lower() == "pagamento" and dados['tipo_pagam'].lower() != filtro_valor.strip().lower():
                continue

            compras_filtradas[id_compra] = dados

        dados_para_exportar = {"compras_filtradas": compras_filtradas}
        mensagem = f"As compras filtradas ({filtro_tipo}={filtro_valor})"

        if not compras_filtradas:
            print("Aviso: Não existem compras com esses filtros para exportar. Ficheiro cancelado.")
            return

#Cenário Extra: Se o utilizador inventar uma entidade
    else:
        print("Erro: A entidade para exportar deve ser 'tudo' ou 'compras'.")
        return

#Tentativa de criação e escrita do ficheiro
    try:
        with open(nome_ficheiro, 'w', encoding='utf-8') as ficheiro:
            json.dump(dados_para_exportar, ficheiro, ensure_ascii=False, indent=4)

        print(f"Sucesso: {mensagem} foram exportados para o ficheiro '{nome_ficheiro}'.")

    except Exception as e:
        print(f"Erro crítico do sistema ao tentar gravar o ficheiro: {e}")

"""# Historico de preços e gráficos"""

def gerar_grafico_evolucao(produto: str, data_inicio: str = "", data_fim: str = ""):
    erros = []
    obj_inicio = None
    obj_fim = None

    if not isinstance(produto, str):
        erros.append("Erro: O nome do produto deve ser texto.")
    elif not produto.strip():
        erros.append("Erro: O nome do produto não pode estar vazio.")

    if data_inicio:
        if not isinstance(data_inicio, str) or not re.match(r"^\d{2}-\d{2}-\d{4}$", data_inicio):
            erros.append("Erro: A data de início deve ser texto no formato DD-MM-YYYY.")
        else:
            try:
                obj_inicio = datetime.strptime(data_inicio, "%d-%m-%Y").date()
            except ValueError:
                erros.append("Erro: Data de início inválida.")

    if data_fim:
        if not isinstance(data_fim, str) or not re.match(r"^\d{2}-\d{2}-\d{4}$", data_fim):
            erros.append("Erro: A data de fim deve ser texto no formato DD-MM-YYYY.")
        else:
            try:
                obj_fim = datetime.strptime(data_fim, "%d-%m-%Y").date()
            except ValueError:
                erros.append("Erro: Data de fim inválida.")

    if obj_inicio and obj_fim and obj_inicio > obj_fim:
        erros.append("Erro: A data de início não pode ser posterior à data de fim.")

    if erros:
        for erro in erros:
            print(f"- {erro}")
        return

    produto_alvo = produto.strip().lower()
    historico = []

    for cid, dados in compras.items():
        if dados['produto'] == produto_alvo:
            data_obj = datetime.strptime(dados['data'], "%d-%m-%Y").date()

            if obj_inicio and data_obj < obj_inicio:
                continue
            if obj_fim and data_obj > obj_fim:
                continue

            historico.append({"data_obj": data_obj, "data_str": dados['data'], "preco": dados['preco']})

    if not historico:
        if data_inicio or data_fim:
            print(f"Erro: Não existem registos de compras para '{produto_alvo.capitalize()}' no período selecionado.")
        else:
            print(f"Erro: Não existem registos de compras para o produto '{produto_alvo.capitalize()}'.")
        return

    historico.sort(key=lambda x: x["data_obj"])

    datas = [item["data_str"] for item in historico]
    precos = [item["preco"] for item in historico]

    print(f"\n--- ANÁLISE DO PRODUTO: {produto_alvo.upper()} ---")
    if len(precos) > 1:
        preco_inicial = precos[0]
        preco_final = precos[-1]
        variacao = ((preco_final - preco_inicial) / preco_inicial) * 100

        print(f"Preço Inicial ({datas[0]}): {preco_inicial:.2f}€")
        print(f"Preço Atual/Final ({datas[-1]}): {preco_final:.2f}€")

        if variacao > 0:
            print(f"Variação: Subiu {variacao:.2f}% ")
        elif variacao < 0:
            print(f"Variação: Desceu {abs(variacao):.2f}% ")
        else:
            print("Variação: O preço manteve-se inalterado. ")
    else:
        print(f"Apenas um registo encontrado: {precos[0]:.2f}€ no dia {datas[0]}.")
        print("Aviso: É necessário pelo menos mais uma compra para calcular a variação de preço.")

    try:
        plt.figure(figsize=(10, 5))
        plt.plot(datas, precos, marker='o', linestyle='-', color='b', linewidth=2, markersize=8)

        titulo = f"Evolução Temporal do Preço: {produto_alvo.capitalize()}"
        if data_inicio or data_fim:
            titulo += f"\n({data_inicio or 'Início'} até {data_fim or 'Fim'})"

        plt.title(titulo, fontsize=14, fontweight='bold')
        plt.xlabel("Data da Compra", fontsize=12)
        plt.ylabel("Preço (€)", fontsize=12)
        plt.grid(True, linestyle='--', alpha=0.7)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

    except Exception as e:
        print(f"Erro ao renderizar o gráfico: {e}")
        print("Certifique-se de que tem a linha 'import matplotlib.pyplot as plt' na sua célula de bibliotecas.")

"""# Consultar estatisticas Globais"""

def consultar_estatisticas():
    print("\n" + "="*45)
    print("   PAINEL DE ESTATÍSTICAS GLOBAIS   ")
    print("="*45)

#Exibição dos Totais Base
    print(f"Total de Utilizadores: {len(utilizadores)}")
    print(f"Total de Lojas Registadas: {len(lojas)}")
    print(f"Total de Compras Realizadas: {len(compras)}")

#Verificação de dados para métricas avançadas
    if not compras:
        print("\nAviso: Ainda não existem compras registadas para gerar métricas agregadas.")
        return

    contagem_lojas = {}
    contagem_produtos = {}
    contagem_users = {}
    gastos_users = {}
    total_gasto = 0.0

#Processamento dos dados de todas as compras
    for dados in compras.values():
        # Contagem para a Loja mais popular
        lid = dados['id_loja']
        contagem_lojas[lid] = contagem_lojas.get(lid, 0) + 1

        # Contagem para o Produto mais vendido
        prod = dados['produto']
        contagem_produtos[prod] = contagem_produtos.get(prod, 0) + 1

        # Contagem e Gastos para o Utilizador
        nif = dados.get('nif_utilizador')
        if nif:
            contagem_users[nif] = contagem_users.get(nif, 0) + 1
            gastos_users[nif] = gastos_users.get(nif, 0.0) + dados['preco']

        # Soma do volume financeiro
        total_gasto += dados['preco']

#Cálculo dos "Vencedores"
    loja_top_id = max(contagem_lojas, key=contagem_lojas.get)
    loja_top = lojas[loja_top_id]
    vendas_loja_top = contagem_lojas[loja_top_id]

    produto_top = max(contagem_produtos, key=contagem_produtos.get)
    vendas_produto_top = contagem_produtos[produto_top]

    # Vencedores dos Utilizadores
    if contagem_users:
        nif_top_compras = max(contagem_users, key=contagem_users.get)
        nif_top_gastos = max(gastos_users, key=gastos_users.get)

        nome_top_compras = utilizadores.get(nif_top_compras, {}).get("nome", "Desconhecido")
        nome_top_gastos = utilizadores.get(nif_top_gastos, {}).get("nome", "Desconhecido")

        vendas_user_top = contagem_users[nif_top_compras]
        gastos_user_top = gastos_users[nif_top_gastos]

#Exibição dos resultados avançados
    print("\n--- MÉTRICAS AGREGADAS AVANÇADAS ---")
    print(f"Loja com mais transações: '{loja_top['nome']}' ({vendas_loja_top} registos)")
    print(f"Produto mais registado: '{produto_top.capitalize()}' ({vendas_produto_top} unidades)")

    if contagem_users:
        print(f"Cliente com mais compras: '{nome_top_compras}' ({vendas_user_top} compras)")
        print(f"Cliente que mais gastou: '{nome_top_gastos}' ({gastos_user_top:.2f}€)")

    print(f"Volume total transacionado registrado na plataforma: {total_gasto:.2f}€")
    print("="*45)

"""# Zona de testes

Teste de Users
"""

# --- DADOS DE TESTE: UTILIZADORES ---
add_user("João Martins", "123456789", "15-05-1990", "M")
add_user("Ana Rita Silva", "234567890", "22-08-1985", "F")
add_user("Carlos Pires", "345678901", "10-12-2000", "M")
add_user("Beatriz Costa", "456789012", "05-03-1998", "F")
add_user("Alex Soares", "567890123", "30-11-2003", "O")
add_user("Rui Figueiredo", "678901234", "14-02-1975", "M")
add_user("Margarida Almeida", "789012345", "25-04-1992", "F")
add_user("Tiago Mendes", "890123456", "09-09-1988", "M")
add_user("Inês Rodrigues", "901234567", "18-07-2001", "F")
add_user("Sam Oliveira", "192837465", "03-01-1995", "O")

# --- DADOS DE TESTE: UTILIZADORES (ERROS) ---

print("\nTeste 1:")
add_user("", "", "", "")

print("\nTeste 2:")
add_user("João M4rtins!!", "987654321", "15-05-1990", "M")

print("\nTeste 3:")
add_user("Ana Sousa", "123", "15-05-1990", "F")

print("\nTeste 4:")
add_user("Carlos Silva", "12345ABCD", "15-05-1990", "M")

print("\nTeste 5:")
add_user("Bruno Alves", 123456789, "15-05-1990", "M")

print("\nTeste 6:")
add_user("Clone do João", "123456789", "10-10-1990", "M")

print("\nTeste 7:")
add_user("Miguel Torres", "234567891", "1990/05/15", "M")

print("\nTeste 8:")
add_user("Erro Temporal", "345678912", "32-05-1990", "M")

print("\nTeste 9:")
add_user("Viajante do Futuro", "456789123", "15-05-2050", "M")

print("\nTeste 10:")
add_user("Alien X", "567891234", "15-05-1990", "Z")

print("\nTeste 11:")
add_user("Tudo Err4d0", "NIF_FALSO", "amanhã", "X")

"""Testes de loja"""

# --- DADOS DE TESTE: LOJA ---
add_loja("Talho Central", "Talho", "Maia")
add_loja("Padaria Pão Quente", "Padaria", "Porto")
add_loja("Mercado da Esquina", "Supermercado", "Lisboa")
add_loja("Peixaria Costa", "Peixaria", "Matosinhos")
add_loja("Frutas & Companhia", "Supermercado", "Faro")

# --- DADOS DE TESTE: LOJA (ERROS) ---

print("\nTeste 1:")
add_loja("", "", "")

print("\nTeste 2:")
add_loja("Supermercado Top!!!", "Supermercado", "Braga")

print("\nTeste 3:")
add_loja("Talho do Bairro", "Talho", "Rua 5")

print("\nTeste 4:")
add_loja("Boutique Chic", "Roupa e Moda", "Coimbra")

print("\nTeste 5:")
add_loja(12345, "Padaria", 4400)

print("\nTeste 6:")
add_loja("Talho Central", "Talho", "Maia")

print("\nTeste 7:")
add_loja("   talho central   ", "Talho", "  MAIA  ")

"""Teste de compras"""

# --- DADOS DE TESTE: COMPRA ---

add_compra("Frango", 3.50, 1, "01-03-2026", "123456789", "N")
add_compra("Frango", 3.80, 2, "10-03-2026", "234567890", "M")
add_compra("Frango", 4.10, 1, "20-03-2026", "345678901")
add_compra("Frango", 3.90, 3, "24-03-2026", "123456789", "n")
add_compra("Leite Magro", 0.90, 2, "15-03-2026", "456789012", "M")
add_compra("Pão de Forma", 1.20, 2, "22-03-2026", "123456789", "N")

# --- DADOS DE TESTE: COMPRA (ERROS) ---

print("\nTeste 1:")
add_compra("", 0, 0, "", "")

print("\nTeste 2:")
add_compra("Arroz", 0, 1, "20-03-2026", "123456789", "M")
add_compra("Arroz", -2.50, 1, "20-03-2026", "123456789", "M")

print("\nTeste 3:")
add_compra("Maçãs @ Promoção!", 1.50, 1, "20-03-2026", "123456789", "N")

print("\nTeste 4:")
add_compra("Bacalhau", 15.00, 999, "20-03-2026", "123456789", "M")

print("\nTeste 5:")
add_compra("Azeite", 4.50, 1, "2026/03/20", "123456789", "M")

print("\nTeste 6:")
add_compra("Manteiga", 2.00, 1, "30-02-2026", "123456789", "N")

print("\nTeste 7:")
add_compra("Cereais", 3.00, 1, "01-01-2050", "123456789", "M")

print("\nTeste 8:")
add_compra("Iogurte", 1.50, 1, "20-03-2026", "123456789", "Cartão")
add_compra("Iogurte", 1.50, 1, "20-03-2026", "123456789", "X")

print("\nTeste 9:")
add_compra("Bolachas", 2.20, 1, "20-03-2026", "999999999", "M")

print("\nTeste 10:")
add_compra("Sumo", 1.80, 1, "20-03-2026", 123456789, "N")

"""Teste de listagem"""

# --- DADOS DE TESTE: LISTAR DADOS ---

listar_dados("utilizadores")
listar_dados("lojas")
listar_dados("compras")

listar_dados("compras", "desc", "produto", "pão de forma")
listar_dados("compras", "asc", "produto", "frango")
listar_dados("compras", "desc", "produto", "leite magro")
listar_dados("compras", "desc", "nif", "123456789")
listar_dados("compras", "asc", "loja", "1")
listar_dados("compras", "desc", "pagamento", "multibanco")
listar_dados("compras", "asc", "pagamento", "numerário")
listar_dados("compras", "desc", "com_pagamento_registado", "sim")

listar_dados("utilizadores", "asc", "sexo", "M")
listar_dados("utilizadores", "desc", "sexo", "F")

listar_dados("lojas", "asc", "especialidade", "talho")
listar_dados("lojas", "desc", "especialidade", "peixaria")

# --- DADOS DE TESTE: LISTAR DADOS (consultar_estatisticas) ---
consultar_estatisticas()

# --- DADOS DE TESTE: LISTAR DADOS (ERROS) ---

print("\nTeste 1:")
listar_dados("produtos")

print("\nTeste 2:")
listar_dados(123)

print("\nTeste 3:")
listar_dados("compras", "cima")

print("\nTeste 4:")
listar_dados("utilizadores", True)

print("\nTeste 5:")
listar_dados("compras", "asc", "produto", "Ferrari")

print("\nTeste 6:")
listar_dados("lojas", "desc", "123!@#", "nada")

"""Teste de gráficos"""

# --- TESTE - GERAR GRÁFICO DE EVOLUÇÃO ---

gerar_grafico_evolucao("Frango")
gerar_grafico_evolucao("Frango","10-03-2026")
gerar_grafico_evolucao("Frango","","20-03-2026")
gerar_grafico_evolucao("Frango","20-03-2026","24-03-2026")

"""Teste de exportação"""

# --- TESTE - EXPORTAR PARA JSON ---

exportar_para_json("backup_projeto.json")
exportar_para_json()
exportar_para_json("frango.json", "compras", "produto", "frango")
exportar_para_json("compras_multibanco.json", "compras", "pagamento", "multibanco")
exportar_para_json("compras_multibanco.json", "compras", "loja","1")